### ISSUE TITLE
new file is open in sublime instance of other workspace

### ISSUE THREAD

**Issue by vryy** [tsantzi/launch_sublime#1]
Hello

I got a problem that when sublime is not the current window in the current workspace, then opening new file will pop the sublime instance in the previous workspace. My machine is Ubuntu 18.04.

Best regards.

**Comment by tsantzi** [comment]
Hi vryy,

Did you make sure to open the file using this custom launcher instead of the default sublime launcher?

I've just tried it in Ubuntu 18.04 with Gnome and it seems to work fine.
